### ISSUE TITLE
Support for Whisper Large-v3

### ISSUE THREAD

**Issue by Sindhu-Hegde** [Blair-Johnson/batch-whisper#15]
Hello, thank you for the code! 
The current codebase only supports upto Whisper Large-v2. However large-v3 has been released now, thus I was wondering if you could add the support to large-v3 as well? It would be really helpful if you could add this support.

Thanks!

**Comment by Blair-Johnson** [comment]
Thanks for your interest, I have no plans to continue supporting this project at the moment. The version of whisper in Transformers supports batch inference and newer model versions. I would recommend using that, as it will have much better long term support.
